### arithmetic operation

In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]
arr1 = np.array(a)
arr2 = np.array(b)

In [3]:
arr1

array([1, 2, 3, 4, 5])

In [4]:
arr2

array([ 6,  7,  8,  9, 10])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
type(arr2)

numpy.ndarray

In [7]:
a+b     # list sum

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [8]:
arr1+arr2    # numpy array sum

array([ 7,  9, 11, 13, 15])

In [9]:
arr1-arr2

array([-5, -5, -5, -5, -5])

In [10]:
arr2-arr1

array([5, 5, 5, 5, 5])

In [12]:
arr2/arr1

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [15]:
arr2//arr1

array([6, 3, 2, 2, 2])

In [16]:
arr2**arr1

array([     6,     49,    512,   6561, 100000])

In [17]:
arr1

array([1, 2, 3, 4, 5])

In [19]:
for i in arr1:
    if i%2==0:
        print(i)

2
4


In [21]:
arr1.append(0)

AttributeError: 'numpy.ndarray' object has no attribute 'append'