In [1]:
import numpy as np

In [2]:
a = np.random.randint(10,50,(4,5))

In [3]:
a

array([[35, 48, 23, 40, 41],
       [20, 42, 19, 29, 34],
       [47, 48, 35, 11, 36],
       [35, 27, 25, 18, 19]])

In [4]:
a>30

array([[ True,  True, False,  True,  True],
       [False,  True, False, False,  True],
       [ True,  True,  True, False,  True],
       [ True, False, False, False, False]])

In [11]:
for i in a[0]:
    print(i,end=" ")

35 48 23 40 41 

In [8]:
a


array([[35, 48, 23, 40, 41],
       [20, 42, 19, 29, 34],
       [47, 48, 35, 11, 36],
       [35, 27, 25, 18, 19]])

In [12]:
np.size(a)

20

In [13]:
np.shape(a)

(4, 5)

In [17]:
bool_arr = a > 30
ans = a[bool_arr]
print(ans)

[35 48 40 41 42 34 47 48 35 36 35]
