In [1]:
import numpy as np


In [15]:
a = np.random.randint(4,10,(1,3))
print(a)

[[9 7 6]]


In [16]:
np.size(a)

3

In [17]:
np.shape(a)

(1, 3)

In [18]:
b = np.random.randint(1,10,(2,3))
b

array([[6, 9, 1],
       [4, 5, 5]])

In [19]:
c = a -b
c

array([[ 3, -2,  5],
       [ 5,  2,  1]])

In [20]:
b-a

array([[-3,  2, -5],
       [-5, -2, -1]])

In [21]:
x = np.random.randint(1,10,(3,4))
x

array([[7, 2, 9, 9],
       [3, 1, 1, 2],
       [9, 1, 7, 3]])

In [22]:
y = np.random.randint(1,20,(4,3))
y

array([[15, 11, 17],
       [12,  8,  6],
       [19, 16,  5],
       [ 6, 13, 12]])

In [23]:
z = x -y

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [24]:
y = np.transpose(y)
y

array([[15, 12, 19,  6],
       [11,  8, 16, 13],
       [17,  6,  5, 12]])

In [25]:
z = x-y

In [26]:
z

array([[ -8, -10, -10,   3],
       [ -8,  -7, -15, -11],
       [ -8,  -5,   2,  -9]])