In [1]:
import numpy as np
a = [1,2,3,4,5,6]
print(type(a))
b = np.array(a)

<class 'list'>


In [2]:
b

array([1, 2, 3, 4, 5, 6])

In [3]:
type(b)

numpy.ndarray

In [4]:
a = [[1,2,3,4,5],[11,22,33,44,55],[111,222,333,444,555]]
nd = np.array(a)

In [5]:
type(nd)

numpy.ndarray

In [6]:
nd

array([[  1,   2,   3,   4,   5],
       [ 11,  22,  33,  44,  55],
       [111, 222, 333, 444, 555]])

In [7]:
nd[1:][1:]

array([[111, 222, 333, 444, 555]])

In [8]:
nd[2][3]

444

In [9]:
nd[2][3]

444

In [10]:
nd[2][4]

555

In [11]:
print(nd[2][0:])

[111 222 333 444 555]


In [12]:
max(b)  # max of element

6

In [13]:
np.argmax(nd)   # return index of max element

14

In [14]:
np.argmin(nd)   # return index of min element

0

In [23]:
np.shape(nd)

(3, 5)

In [24]:
np.size(nd)

15