### Numpy is faster then list

In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5,6]
b = np.array(a,dtype=int)

In [3]:
print(b)

[1 2 3 4 5 6]


In [4]:
type(b)

numpy.ndarray

In [5]:
b = np.ones(4,dtype=int)
b

array([1, 1, 1, 1])

In [6]:
b = np.zeros(6,dtype=float)
b

array([0., 0., 0., 0., 0., 0.])

In [7]:
b = np.full(3,5)   # size is 3 having each element is 5
b

array([5, 5, 5])

In [8]:
#2d
b = np.ones((2,3),dtype=int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [9]:
b = np.zeros((3,2),dtype=int)
b

array([[0, 0],
       [0, 0],
       [0, 0]])

In [10]:
b = np.full((5,3),52)
b

array([[52, 52, 52],
       [52, 52, 52],
       [52, 52, 52],
       [52, 52, 52],
       [52, 52, 52]])

In [11]:
type(b)

numpy.ndarray

In [12]:
b

array([[52, 52, 52],
       [52, 52, 52],
       [52, 52, 52],
       [52, 52, 52],
       [52, 52, 52]])

In [13]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
b = np.arange(2,20,2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
type(b)

numpy.ndarray

In [16]:
b = np.linspace(2,10)
b

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [17]:
b[1]-b[0]

0.16326530612244916

In [18]:
b[2]-b[1]

0.16326530612244872

In [19]:
b = np.linspace(1,20)
b

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [20]:
b = np.identity(5,dtype=int)  #it will generate identity matrix
b

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [21]:
b = np.eye(6,9,dtype=int)
b

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0]])

In [22]:
 b.shape

(6, 9)

In [23]:
b.size

54

In [24]:
b = np.random.rand(4)
b

array([0.88125168, 0.61683778, 0.06551554, 0.59892193])

In [25]:
b = np.random.rand(9)*10
b

array([3.75314154, 8.99570947, 7.07998384, 8.85325907, 1.34644706,
       8.53862388, 5.14055675, 9.27485689, 0.86191894])

In [26]:
b = np.random.randint(100)
b

11

In [27]:
b = np.random.randint(19,size=(4,5))
b

array([[ 6,  9,  3,  2,  5],
       [10,  5,  8,  6,  0],
       [15,  6, 14,  8,  7],
       [17, 18,  8, 10, 11]])

In [28]:
b.dtype

dtype('int64')